version: 0.2
# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax
phases:
  build:
    on-failure: ABORT
    commands:
      - echo "Starting SAM packaging `date` in `pwd`"
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-ap-south-1-511954746917 --output-template-file packaged.yaml
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"
artifacts:
  type: zip
  files: 
    - template.yaml
    - packaged.yaml
